### ISSUE TITLE
Add Axiom

### ISSUE THREAD

**Issue by StillLutto** [JosTheDude/developer-toolkit#1]
Simple as that, I don't think any further information is needed here.

**Comment by JosTheDude** [comment]
Thank you for your suggestion @StillLutto.

I have a couple of questions, as I don't have any personal experience with Axiom.

- Isn't this a mod that is required on the servers one joins?
- If it isn't, how does the mod work in multiplayer contexts without the mod installed on the server?

**Comment by StillLutto** [comment]
@JosTheDude No, it won't do anything if the server doesn't have the plugin/mod itself.

**Comment by JosTheDude** [comment]
Merging Suggestion into #3
