### ISSUE TITLE
New mods

### ISSUE THREAD

**Issue by StillLutto** [JosTheDude/developer-toolkit#3]
Here is a list of useful QoL mods to could be looked into adding:
- Client Side Noteblocks - https://modrinth.com/mod/clientsidenoteblocks
- Disable Insecure Chat Toast - https://modrinth.com/mod/disableinsecurechattoast
- Fast IP Ping - https://modrinth.com/mod/fast-ip-ping
- Isometric Renders - https://modrinth.com/mod/isometric-renders
- No Resource Pack Warnings - https://modrinth.com/mod/no-resource-pack-warnings
- Nvidium - https://modrinth.com/mod/nvidium
- Flashback - https://modrinth.com/mod/flashback
- Server Pack Unlocker - https://modrinth.com/mod/server-pack-unlocker
- Tweakeroo - https://modrinth.com/mod/tweakeroo
- Bobby - https://modrinth.com/mod/bobby
- Camera Utils - https://modrinth.com/mod/camera-utils
- Chat Calc - https://modrinth.com/mod/chat-calc
- Chat Signing Hider - https://modrinth.com/mod/chat-signing-hider
- Chunky - https://modrinth.com/mod/chunky
- Command Keys - https://modrinth.com/mod/command-keys
- Karn's Useful Command - https://modrinth.com/mod/karns-useful-command
- Show Me Your Skin - https://modrinth.com/mod/show-me-your-skin
- Sodium Shadowy Path Blocks - https://modrinth.com/mod/sodium-shadowy-path-blocks

Some of these mods are not officially supported for 1.21.1, but are for 1.21 and still work on 1.21.1.

**Comment by StillLutto** [comment]
Oh, and if you can, add https://ui-utils.com/ to the list. It isn't on modrinth though

**Comment by JosTheDude** [comment]
> Oh, and if you can, add https://ui-utils.com/ to the list. It isn't on modrinth though

It's extremely buggy and it against Modrinth rules hence why I didn't add it. I install it personally though.

**Comment by JosTheDude** [comment]
Thank you for all the mod suggestions, I will review them soon <3

**Comment by JosTheDude** [comment]
Add Axiom -- additional mod suggestion

**Axiom has been approved and added**

**Comment by JosTheDude** [comment]
* Client Side Noteblocks - https://modrinth.com/mod/clientsidenoteblocks
As this modpack is for server development, I would say that being able to hear when noteblocks have lag on the client may have benefits for this pack's users over them being played client sided as the usecase is a bit limited.
* Disable Insecure Chat Toast - https://modrinth.com/mod/disableinsecurechattoast
Same as the point above -- developer's may want to see when the toast pops up to test plugins such as AntiPopup or similar.
* Fast IP Ping - https://modrinth.com/mod/fast-ip-ping
I tried out this mod but on my personal client is flat out broke server pinging -- how does it work for you?
* Isometric Renders - https://modrinth.com/mod/isometric-renders
No 1.21.1 support -> will add when we go to a 1.21.4 update
* No Resource Pack Warnings - https://modrinth.com/mod/no-resource-pack-warnings
Not being added, same reason for *Disable Insecure Chat Toast*
* Nvidium - https://modrinth.com/mod/nvidium
This is more client-sided and bars out AMD users (I'm one of em') so as of now not slated to be added
* Flashback - https://modrinth.com/mod/flashback
Added <3 Thank you for the suggestion!!
* Server Pack Unlocker - https://modrinth.com/mod/server-pack-unlocker
Added <3 Thank you for suggestion :D
* Tweakeroo - https://modrinth.com/mod/tweakeroo
Beautiful. Added but also added to the "Risk of Punishment" list :)
Dependency: MaLaLib was added alongside this
* Bobby - https://modrinth.com/mod/bobby
Not really in the mission scope of the pack so I've decided to leave this and Distant Horizons for players to install if they'd like.
* Camera Utils - https://modrinth.com/mod/camera-utils
I love this but it didn't work on the pack previously -- have you tested it on your client?
* Chat Calc - https://modrinth.com/mod/chat-calc
Use Client Command's Calculator (/ccalc)
* Chat Signing Hider - https://modrinth.com/mod/chat-signing-hider
Same reason for the Disable Insecure Chat Toast.
* Chunky - https://modrinth.com/mod/chunky
Added :D
* Command Keys - https://modrinth.com/mod/command-keys
Invalid link
* Karn's Useful Command - https://modrinth.com/mod/karns-useful-command
Server Sided. Client-Commands includes a bunch of these on the client, though.
* Show Me Your Skin - https://modrinth.com/mod/show-me-your-skin
Same reason for Bobby.
* Sodium Shadowy Path Blocks - https://modrinth.com/mod/sodium-shadowy-path-blocks
Same reason for Bobby.

**Added** (thank you for suggesting!! <3)
* Flashback - https://modrinth.com/mod/flashback
Added <3 Thank you for the suggestion!!
* Server Pack Unlocker - https://modrinth.com/mod/server-pack-unlocker
Added <3 Thank you for suggestion :D
* Tweakeroo - https://modrinth.com/mod/tweakeroo
Beautiful. Added but also added to the "Risk of Punishment" list :)
Dependency: MaLaLib was added alongside this
* Chunky - https://modrinth.com/mod/chunky
Added :D

**Slated for Version Update**
* Isometric Renders - https://modrinth.com/mod/isometric-renders
No 1.21.1 support -> will add when we go to a 1.21.4 update

**Additional Info Requested**
* Fast IP Ping - https://modrinth.com/mod/fast-ip-ping
I tried out this mod but on my personal client is flat out broke server pinging -- how does it wrok for you?
* Camera Utils - https://modrinth.com/mod/camera-utils
I love this but it didn't work on the pack previously -- have you tested it on your client?
* Command Keys - https://modrinth.com/mod/command-keys
Invalid link

**Comment by JosTheDude** [comment]
Accidentally closed.

**Comment by StillLutto** [comment]
@JosTheDude Sorry, I didn't see you had responded to this!
Here is the requested info:
- Fast IP Ping: I've never had any issues with it and quite liked it, but if it is buggy on your client, then I wouldn't add it.
- Camera Utils: Seems to work fine for me using the base pack.
- Command Keys: Here is the correct link: https://modrinth.com/mod/commandkeys

**Comment by JosTheDude** [comment]
Adding https://modrinth.com/mod/chunk-debug to this list as per Jenkin's suggestion.
- Single-player / server-based chunk debug tool. Just useful for single player worlds mostly.

**Comment by Dawsson** [comment]
A mod that allows you to press ctrl + r to refresh servers would be really nice

**Comment by StillLutto** [comment]
> A mod that allows you to press ctrl + r to refresh servers would be really nice

Found this: https://modrinth.com/mod/reload-server-list/

**Comment by JosTheDude** [comment]
> > A mod that allows you to press ctrl + r to refresh servers would be really nice
> 
> Found this: https://modrinth.com/mod/reload-server-list/

Added! Thank you <3

**Comment by JosTheDude** [comment]
@StillLutto This modpack is now updated and options will now persist across updates and reinstalls.

Thank you for your suggestions <3

Please let me know if there's any issues!!
